<!-- Start Footer section -->
        <footer class="footer">
            <!-- start container -->
            <div class="container">
                <!-- start row -->
                <div class="row">
                    <!-- start phone number -->
                    <div class="col-xs-12 col-sm-6 col-lg-3">
                        <a href="#" class="hover-animate">
                            <span class="ukie-icons hover-animate"><i class="fa fa-phone"></i></span> (+51) 927163859
                        </a>
                    </div>
                    <!-- end phone number -->
                    <!-- start email -->
                    <div class="col-xs-12 col-sm-6 col-lg-3">
                        <a href="mailto:info@ottodavilaflores.com" class="hover-animate">
                            <span class="ukie-icons hover-animate"><i class="fa fa-paper-plane"></i></span> info@ottodavilaflores.com
                        </a>
                    </div>
                    <!-- end email -->
                    <!-- start address -->
                    <div class="col-xs-12 col-sm-6 col-lg-3">
                        <a href="#" class="hover-animate">
                            <span class="ukie-icons hover-animate"><i class="fa fa-map-marker"></i></span> Juan Fuentes 286, Surquillo
                        </a>
                    </div>
                    <!-- end address -->
                    <!-- start Copyright -->
                    <div class="col-xs-12 col-sm-6 col-lg-3 text-right">
                        <span class="copyright">Copyright © 2018 All right reserved</span>
                    </div>
                    <!-- end Copyright -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </footer>
        <!-- End Footer section -->

    </div>
    <!-- Scroll to Top -->
    <a href="#" class="btn scrollToTop"><i class="fa fa-angle-up"></i></a>
    <!-- End Scroll to Top -->

    <!-- Scripts -->
    <script src="assets/js/jquery-1.11.2.min.js" type="text/javascript"></script>
    <script src="assets/boostrap-files/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="assets/js/jquery.appear.js" type="text/javascript"></script>
    <script src="assets/js/jquery.nicescroll.min.js" type="text/javascript"></script>
    <script src="assets/js/jquery.mixitup.min.js" type="text/javascript"></script>
    <script src="assets/js/jquery.magnific-popup.min.js" type="text/javascript"></script>
    <script src="assets/js/owl.carousel.min.js" type="text/javascript"></script>
    <script src="assets/js/jquery.inview.min.js" type="text/javascript"></script>
    <script src="assets/js/jquery.knob.min.js" type="text/javascript"></script>
    <script src="assets/js/jquery.cookie.js" type="text/javascript"></script>
    <script src="assets/js/scripts.js" type="text/javascript"></script>